[package]
name = "Examples"
version = "0.0.0"

[addresses]
chain_tune = "_"
source_addr="0x242c026099140c0d787faf9da562d0aace66700666a4d8fd80dab86756b31660"
std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
aptos_token = "0x3"

[dependencies]
AptosFramework = {local= "C:/Users/Asus/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-framework"}
AptosStdlib = {local="C:/Users/Asus/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-stdlib"}
AptosToken={local="C:/Users/Asus/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-token"}